executable = ./condor_test_nuus.sh
arguments = $(filename)

error  = $(filename).err
output = $(filename).out
log    = condor_test_nuus.log

notification = Complete
# notify_user = xchen168@syr.edu

# 45466 for better gpu
requirements = (CUDAGlobalMemoryMb >= 22699) && (CUDAGlobalMemoryMb < 40000)
+request_gpus = 1

# Limits this specific submission to x jobs running at once
# max_idle = 32
# concurrency_limits = MyLimit:32


# queue filename matching files test_nuus_inputs/vanilla_ppo/hopper_vanilla_ppo_5c8de009-b865-4c1b-b311-375f5978186c_beta=2.0.input
# queue filename matching files test_nuus_inputs/vanilla_ppo/*.input
queue filename matching files test_nuus_inputs/vanilla_ppo/hopper*5c8de009-b865-4c1b-b311-375f5978186c*.input
queue filename matching files test_nuus_inputs/vanilla_ppo/hopper*5ef44dd2-4893-4f93-ab17-50717a8a9243*.input